apiVersion: apps/v1

kind: Deployment

metadata:
  name: webapp

  namespace: webapp

spec:

  replicas: 5

  selector:

    matchLabels:

      app: webapp

  template:

    metadata:

      labels:

        app: webapp

    spec:

      containers:

      - name: webapp

        image: acrakspoc01.azurecr.io/webapp:768ca85e976b174c9d11b5c36bd976dfde4baca8

        imagePullPolicy: Always

        ports:

        - containerPort: 3000