apiVersion: apps/v1

kind: Deployment

metadata:
  name: webapp

  namespace: webapp

spec:

  replicas: 5

  selector:

    matchLabels:

      app: webapp

  template:

    metadata:

      labels:

        app: webapp

    spec:

      containers:

      - name: webapp

        image: acrakspoc01.azurecr.io/webapp:0e009e59f483b447c26348fe2c970f5e6b1a5730

        imagePullPolicy: Always

        ports:

        - containerPort: 3000