apiVersion: apps/v1

kind: Deployment

metadata:
  name: webapp

  namespace: webapp

spec:

  replicas: 3

  selector:

    matchLabels:

      app: webapp

  template:

    metadata:

      labels:

        app: webapp

    spec:

      containers:

      - name: webapp

        image: acrakspoc01.azurecr.io/webapp:v1

        imagePullPolicy: Always

        ports:

        - containerPort: 3000